"""Provider-agnostic object storage for uploaded screenshots (TZ section 10:
"secure object storage"). LocalFilesystemStorage is a dev/MVP fallback — an
S3-compatible implementation slots in behind the same interface without
touching callers."""

from __future__ import annotations

import asyncio
from abc import ABC, abstractmethod
from pathlib import Path


class ScreenshotStorage(ABC):
    @abstractmethod
    async def save(self, key: str, data: bytes) -> None: ...

    @abstractmethod
    async def delete(self, key: str) -> None: ...


class LocalFilesystemStorage(ScreenshotStorage):
    def __init__(self, base_dir: Path) -> None:
        self._base_dir = base_dir
        self._base_dir.mkdir(parents=True, exist_ok=True)

    def _path_for(self, key: str) -> Path:
        # `key` is always generated by us (uuid-based, see
        # app.ai.screenshot_pipeline) - never taken from user input - so a
        # plain join is safe here.
        path = self._base_dir / key
        path.parent.mkdir(parents=True, exist_ok=True)
        return path

    async def save(self, key: str, data: bytes) -> None:
        await asyncio.to_thread(self._path_for(key).write_bytes, data)

    async def delete(self, key: str) -> None:
        path = self._path_for(key)
        if path.exists():
            await asyncio.to_thread(path.unlink)
